# Generated by Django 5.0.1 on 2024-02-26 01:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacion', '0003_alter_consultorio_options_alter_especialidad_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Paciente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('apellido', models.CharField(max_length=50)),
                ('dni', models.IntegerField()),
                ('telefono', models.IntegerField()),
                ('obrasocial', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'paciente',
                'verbose_name_plural': 'Pacientes',
                'ordering': ['apellido', 'nombre'],
            },
        ),
    ]
